/**
 * @authro yudong
 * @date 2018/12/7
 */
export const AXIOS_TIMEOUT = 3000
export const APP_CONTEXT = '/onlineExam'
export const GET_BANNER_LIST_URL = '/banner/getBannerList'
export const LOGIN_URL = '/core/login'
export const LOGOUT_URL = '/core/logout'
export const GET_MENUS_LIST = '/core/menus/getMenusList'
export const GET_PROPERTY_SOURCE_NAMES = '/actuator/env'
export const GET_MAPPINGS = '/actuator/mappings'
export const GET_CONFIGPROPS = '/actuator/configprops'
export const GET_CONDITIONS = '/actuator/conditions'
export const GET_BEANS = '/actuator/beans'
export const GET_LOGGERS = '/actuator/loggers'
export const GET_HEAPDUMP = '/actuator/heapdump'
export const GET_JPS = '/actuator/jps'
export const GET_JINFO = '/actuator/jinfo'
export const GET_PRINTFLAGSFINAL = '/actuator/printFlagsFinal'
export const GET_METRICS = '/actuator/metrics'
export const GET_THREADS = '/actuator/threaddump'
export const FIND_USERS = '/admin/users/findUsers'
export const CHANGE_USERSE_NABLED = '/admin/users/changeUsersEnabled'
export const EDIT_USERS = '/admin/users/editUsers'
export const CREATE_USERS = '/admin/users/createUsers'
export const UPDATE_USERS_PASSWORD = '/admin/users/updateUsersPassword'
export const DELETE_USERS = '/admin/users/deleteUsers'
export const UPLOAD_FILE = '/core/files/uploadFile'
export const DOWNLOAD_FILE = '/core/files/downloadFile'
export const FIND_USERS_AUTHORITIES = '/admin/authorities/findUsersAuthorities'
export const FIND_AUTHORITIES = '/admin/authorities/findAuthorities'
export const AUTH_USERS = '/admin/authorities/authUsers'
export const UN_AUTH_USERS = '/admin/authorities/unAuthUsers'
