### 请先调用此接口登录
POST {{url}}/onlineExam/core/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

#username=admin&password=admin&submit=Login
username=admin&password=admin&submit=Login&coreRememberMe=true

> {%
    var headers = response.headers;
    var headerStr = headers.toString();
    var headerArr = headerStr.split(/[\r\n]/m);
    var HEADERS = [];
    for (var i = 0; i < headerArr.length; i++) {
        var tmpArr = headerArr[i].split(':');
        if (!HEADERS[tmpArr[0]]) {
            HEADERS[tmpArr[0]] = [];
        }
        HEADERS[tmpArr[0]] = HEADERS[tmpArr[0]].concat(tmpArr[1]);
    }
    function getCookieValue(HEADERS, cookieName) {
        var setCookies = HEADERS['Set-Cookie'];
        for (var i = 0; i < setCookies.length; i++) {
            var cookies = setCookies[i].split(';')[0].split('=');
            var name = cookies[0];
            var value = cookies[1];
            if (cookieName === name.trim()) {
                return value;
            }
        }
    }
    client.global.set("CORE_REMEMBER_ME", getCookieValue(HEADERS,"CORE_REMEMBER_ME")); //关闭IDEA后才会失效
    print(client.global.get("CORE_REMEMBER_ME"));

    client.global.set("SESSION", getCookieValue(HEADERS,"SESSION")); //关闭IDEA后才会失效
    print(client.global.get("SESSION"));
%}

###
GET {{url}}/onlineExam/actuator/threaddump
Accept: application/json,*/*
Content-Type: application/json
Cookie: SESSION={{SESSION}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

###
